version: '3'
services:
  code-challenge-api:
    build:
      context: ./
    container_name: code-challenge-api

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8080:8080"
    depends_on:
      - code-challenge-api